name: Build Rock5b Armbian Kernel

# 触发条件：手动触发（workflow_dispatch）+ 可选定时触发（schedule）
on:
  workflow_dispatch:  # 手动触发（推荐）
  # schedule:
  #   - cron: '0 0 * * 0'  # 每周日凌晨编译一次（可选）

# 作业配置
jobs:
  build-kernel:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Clone Armbian Build
        run: |
          git clone https://github.com/armbian/build
          cd build
          ./compile.sh kernel BOARD=rock-5b BRANCH=edge KERNELBRANCH="tag:v7.0-rc3" KERNEL_MAJOR_MINOR=7.0 


      # 步骤6：上传产物到GitHub Artifact（可下载）
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rock5b-mainline-kernel
          path: output/packages-hashed/*
          retention-days: 7  # 产物保留7天（可调整）